plugins {
    id "com.android.library"
}

android {
    namespace "com.frontierrift.uninstall"
    compileSdk 35

    defaultConfig {
        minSdk 24
        targetSdk 35
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

base {
    archivesName = "riftuninstall"
}

dependencies {
    compileOnly "org.godotengine:godot:4.7.2.stable"
}
